"""empty message

Revision ID: 0cdc215868ce
Revises: 1d6ba263d501
Create Date: 2016-04-03 16:23:06.105439

"""

# revision identifiers, used by Alembic.
revision = '0cdc215868ce'
down_revision = '1d6ba263d501'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_nickname', table_name='user')
    op.create_unique_constraint(None, 'user', ['nickname'])
    op.create_unique_constraint(None, 'user', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=True)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_table('post')
    ### end Alembic commands ###
